### ISSUE TITLE
session数据串岗了

### ISSUE THREAD

**Issue by zhenyangze** [huang-yi/laravel-swoole-http#10]
原有接口使用的session数据来区分不同的用户，使用laravel-swoole-http后，任何人登录后，所有端的用户信息都变成一样的了。

**Comment by huang-yi** [comment]
如果你使用的是Laravel自己的session和auth组件，应该不会出现用户身份错乱的情况（这个包实现了自动重置session，默认也会重置auth组件）。

如果不是的话，[`swoole.resets`](https://github.com/huang-yi/laravel-swoole-http/blob/master/README-cn.md#resets)这个配置项或许可以帮助到你。

或者你可以详细描述一下你的使用场景，我们讨论一下。

**Comment by zhenyangze** [comment]
测试代码：
```php
Route::get('/show/{id}', function($id) {
    if (!session($id)) {
        session([
            $id => $id,
        ]);
    }
    return $id . ":" . session($id);
});
```

用不同浏览器访问，结果出现
```
1：1
2：1
3：2
4：1
```

**Comment by huang-yi** [comment]
请问一下你的laravel-swoole-http是否为最新的3.1.0？因为之前的老版本都需要自己手动重置session。

如果已经是使用的最新版，那么请把你的Laravel版本号告诉我，我做下测试。

**Comment by zhenyangze** [comment]
| PHP               | 7.1.3   |
| Swoole            | 4.0.3   |
| Laravel Framework | 5.6.7   |

**Comment by huang-yi** [comment]
你好，我在本地构造了与你一样的环境并粘贴了你所提供的代码做了测试，利用多个浏览器打，输出的值并未发生错乱。

我们继续排查一下问题：

1、再次确认laravel-swoole-http的版本为3.1.0
2、请确保你启动session的中间件为默认的`\Illuminate\Session\Middleware\StartSession::class`

**Comment by zhenyangze** [comment]
1、composer配置： "huang-yi/laravel-swoole-http": "^3.1"，

2、Illuminate\Session\SessionServiceProvider::class,

确认没有问题，而且系统用的是laravel5.6的原生包。

**Comment by zhenyangze** [comment]
这段时间composer国内源一直没更新，跟这个有关系吗？

**Comment by huang-yi** [comment]
你可以替换成这个源试试：

```
composer config -g repo.packagist composer https://packagist.laravel-china.org
```

**Comment by huang-yi** [comment]
我想我已经找到问题的答案了。

**问题的关键在于你的测试代码中，往session中存储的数组的键为数字键，就是因为这个数字键造成了结果的错乱。**

而造成这个错乱的元凶不是`laravel-swoole-http`，而是Laravel本身。Laravel在load session的时候会做一个`array_merge`操作，这个`array_merge`操作正是造成结果错乱的关键，源码是这样的：

```php
<?php

/**
 * Load the session data from the handler.
 *
 * @return void
 */
protected function loadSession()
{
    $this->attributes = array_merge($this->attributes, $this->readFromHandler());
}
```

我们知道，PHP中`array_merge`函数会重置数组的下标，所以当你访问`/show/1`后，session里的存储的值为：

```php
[
    1 => 1
]
```

但是当我们访问`/show/2`时，Laravel读取的session值为：

```php
// array_merge后下标被重置了
[
   0 => 1
]
```

然后再将2存储进去，就是：

```php
[
   0 => 1,
   2 => 2,
]
```

由于每次读取都会被重置下标，所以就会造成后续访问的结果错乱。

所以，即使你使用传统的nginx + php-fpm的方式来访问这份测试代码，结果也是一样会错乱的。

**结论：**

我们在写session的时候，一定不要使用数字作为存储的键。

-------------------------

我们可以稍稍修改一下那份测试代码：

```php
Route::get('/show/{id}', function($id) {
    $key = 'item' . $id;

    if (!session($key)) {
        session([
            $key => $id,
        ]);
    }
    return $id . ":" . session($key);
});
```

这样就不会错乱了。

**Comment by zhenyangze** [comment]
确实有这部分原因:-）

然后我在代码基础上修改了下key的赋值操作
```
$key => $id .  '-' . rand(10, 100) // 这里加了随机数
```

然后查看效果（chrome都是隐身模式）

[![P6lRHS.md.jpg](https://s1.ax1x.com/2018/08/10/P6lRHS.md.jpg)](https://imgchr.com/i/P6lRHS)

**Comment by huang-yi** [comment]
Review了一下代码，发现之前清理session的前提条件判断有点小疏漏，现已优化，可以查看这个[#commit](https://github.com/huang-yi/laravel-swoole-http/commit/03c43814fab966a70f9b69b43bcffb0e0938ef52#diff-ed69664805a4caa6fda0dce9df3a0c5a)。

而且之前的逻辑只清理了默认session驱动，现在会清理所有驱动。

然后你update一下`laravel-swoole-http`，清除一下cookie即可。

你可以再做一次测试，非常感谢你的反馈。

**Comment by zhenyangze** [comment]
赞👍🏻
