### ISSUE TITLE
Call to undefined function swoole_cpu_num()

### ISSUE THREAD

**Issue by zhenyangze** [huang-yi/laravel-swoole-http#11]
#### 错误信息

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function swoole_cpu_num()
```

#### 文件
huang-yi/laravel-swoole-http/config/swoole.php

#### 说明
在mac电脑上，swoole_cpu_num是不支持的，需要判断这个方法是否存在。

类似的还有
```php
swoole_set_process_name
cli_set_process_title
apc_clear_cache
opcache_reset
```

**Comment by huang-yi** [comment]
- `swoole_cpu_num`在mac下使用应该没问题哦，我也是在mac上开发的
- `swoole_set_process_name`这个函数有做判断，MacOS下不会调用该函数
- 至于`apc_clear_cache`和`opcache_reset`也有相应的method_exists判断

**Comment by zhenyangze** [comment]
找不到刚才的记录了。
swoole_cpu_num 这个方法是支持的。
但是我需要swoole和php-fpm同时支持，有些laravvel后台的代码还不能迁移到swoole环境中。
在php-fpm环境中，会遍历配置文件，包括读取`laravel-swoole-http/config/swoole.php`这个文件，导致swoole_cpu_num方法找不到。

**Comment by zhenyangze** [comment]
嗯，相当于是个兼容性的建议吧。

**Comment by huang-yi** [comment]
非常感谢~
