### ISSUE TITLE
疑惑： $this->container['events']->fire('http.start', func_get_args())

### ISSUE THREAD

**Issue by 839891627** [huang-yi/laravel-swoole-http#8]
没找到这个事件是在哪里定义的？ **http.start**这是laravel事件，不是 **swoole**事件？所以我没找到。。

**Comment by huang-yi** [comment]
你好， **http.*** 系列的事件是该拓展包自定义的事件。目的是为使用者在swoole-http-server生命周期运行过程中注入自定义的代码逻辑提供入口，使用者只需要为这个事件绑定相应的Listener即可。

另外，Laravel中`string`类型的事件不需要额外定义，也就是说fire的时候就完成定义了。

**Comment by 839891627** [comment]
> 使用者只需要为这个事件绑定相应的Listener即可。

是说 **http**.*这里，扩展包自身并没有去 listen，只是开放给使用者按需使用？我理解对吗？

**Comment by huang-yi** [comment]
对，这个设计主要是为了提高可拓展性。
